### ISSUE TITLE
Bot account banned from speaking

### ISSUE THREAD

**Issue by RebelliousUno** [RebelliousUno/EmeraldOrSilverfish#3]
The bot can't speak in twitch right now....hopefully this is a softban

Get the bot to stop responding to ^emerald and ^silverfish

**Comment by keab42** [comment]
Might be an idea to have the bot whisper to folks.

**Comment by RebelliousUno** [comment]
Yeah, so I think it got throttled, it can speak again now.
I'm going to remove the response...
I did try whispers but it wouldn't send

**Comment by RebelliousUno** [comment]
API limits have been released as it's not a verified bot account

**Comment by RebelliousUno** [comment]
I did this a bit ago
